# Generated by Django 5.1.6 on 2026-02-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('dob_date', models.DateField()),
                ('email_id', models.EmailField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('contact_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
