# Generated by Django 5.1.6 on 2026-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_years',
            field=models.PositiveIntegerField(blank=True, help_text='Enter warranty in years (leave blank if no warranty)', null=True),
        ),
    ]
