# Generated by Django 5.1.6 on 2026-02-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
