# Generated by Django 5.1.6 on 2026-02-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_review_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='gst',
            new_name='cgst',
        ),
        migrations.AddField(
            model_name='order',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
