from django.urls import path
from . import views
from django.contrib import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('faqs/', views.faqs, name='faqs'),
    path('register/', views.registration, name='registration'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('change-password/', views.change_password, name='change_password'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('verify-reset-otp/', views.verify_reset_otp, name='verify_reset_otp'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('user-details/', views.user_details, name='user_details'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    #path('category/<int:id>/', views.category_detail, name='category_detail'),
    # path('category/<slug:slug>/', views.product_list_by_category, name='product_list_by_category'),
    #path('category/<int:id>/', views.category_detail, name='category_detail'),
    path('category/<int:id>/', views.product_list, name='product_list'),
    path('product/<int:id>/', views.product_detail, name='product_detail'),
    path('category/<int:id>/', views.category_products, name='category_products'),
    path('wishlist/', views.wishlist_page, name='wishlist'),
    path('add-to-wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove-from-wishlist/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('cart/', views.cart_page, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update-cart/<int:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('remove-cart/<int:product_id>/', views.remove_cart, name='remove_cart'),
    path('checkout/', views.checkout_page, name='checkout'),
    path('order-success/<int:order_id>/', views.order_success, name='order_success'),
    path("payment-success/", views.payment_success, name="payment_success"),
    path("my-orders/", views.order_history, name="order_history"),
    path("order/<int:order_id>/", views.order_detail, name="order_detail"),
    path("track-order/<int:order_id>/", views.track_order, name="track_order"),
    path('my-warranties/', views.my_warranties, name='my_warranties'),
    path('review/edit/<int:review_id>/', views.edit_review, name='edit_review'),
path('review/delete/<int:review_id>/', views.delete_review, name='delete_review'),
path("search/", views.search, name="search"),
path("invoice-html/<int:order_id>/", views.invoice_view, name="invoice_html"),
path('cancel-order/<int:order_id>/', views.cancel_order, name='cancel_order'),


####################### ADMIN 

path("panel/login/", views.admin_login, name="admin_login"),
path("panel/dashboard/", views.admin_dashboard, name="admin_dashboard"),
path("panel/logout/", views.admin_logout, name="admin_logout"),
path("panel/users/", views.manage_users, name="manage_users"),
path("panel/users/delete/<int:user_id>/", views.delete_user, name="delete_user"),
path("panel/reviews/", views.manage_reviews, name="manage_reviews"),
path("panel/categories/", views.manage_categories, name="manage_categories"),
path("panel/features/", views.manage_features, name="manage_features"),
path("panel/products/", views.manage_products, name="manage_products"),
path("panel/stock/", views.manage_stock, name="manage_stock"),
path("panel/product-images/<int:product_id>/",views.manage_product_images,name="manage_product_images"),
path("panel/orders/", views.manage_orders, name="manage_orders"),
path( "panel/orders/<int:order_id>/details/",views.get_order_details,name="get_order_details"),
path("panel/revenue/", views.revenue_dashboard, name="revenue_dashboard"),
path("panel/reports/", views.admin_reports, name="admin_reports"),
path("panel/reports/download/", views.download_report, name="download_report"),
path("panel/reports/download/pdf/", views.download_report_pdf, name="download_report_pdf"),
]
